.pragma library

var HEADER_HEIGHT = 70;
var HEAD_PIC_WIDTH = 50;
var HEADER_COLOR = '#2047B0';
var HEADER_PRESSED_COLOR = '#7DB2FF';

var NORMAL_MARGIN = 10;
var LARGE_MARGIN = 15;
var SMALL_MARGIN = 5;

var ITEM_BACKGROUND_COLOR = "transparent";
var ITEM_SELECTED_BACKGROUNT_COLOR = "#3D3D3D";

var ITEM_MARGIN = 16;
var LIST_DRAG_DISTANCE = -120;

var DEFAULT_FONT_SIZE = 24;
var FONT_SIZE_SMALLER = 20;
var FONT_SIZE_LARGE = 32;

var PHOTO_SIDE_NORMAL_LEN = 180;
var PHOTO_SIDE_SMALL_LEN = 120;
var PHOTO_SIDE_LARGE_LEN = 240;
var SCREEN_WIDTH = 480;
var SCREEN_HEIGHT = 854

var BALLOON_BOX_BORDER_LEN = 18;
var NORMAL_BTN_ROW_WIDTH = 200;
var USER_HOME_HEADPIC_WIDTH = 100;
